on: push
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      # - name: Clang Format
      #   uses: RafikFarhad/clang-format-github-action@3.2
      - name: Execute the checks
        run: |
          sh ./tests/push_check.sh

