on: push
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
        shell: bash
    steps:
      - name: Simple ls
        run: |
          ls -la
          pwd
      - name: Check for example
        run: |
          chmod +x check.sh
          ./chech.sh
