on: push
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Simple ls
        run: |
          ls -la
          pwd
          tree
      - name: root
        run: |
          sh ./test.sh
      - name: Check for example
        run: |
          sh ./scripts/chech.sh
